# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/psf/iCloud/UCLA/Courses/csm152a/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_12/blk_mem_input_weights_12.xci
# IP: The module: 'blk_mem_input_weights_12' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/psf/iCloud/UCLA/Courses/csm152a/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_12/blk_mem_input_weights_12_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_input_weights_12'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /media/psf/iCloud/UCLA/Courses/csm152a/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_12/blk_mem_input_weights_12.xci
# IP: The module: 'blk_mem_input_weights_12' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/psf/iCloud/UCLA/Courses/csm152a/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_12/blk_mem_input_weights_12_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_input_weights_12'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
