# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/psf/iCloud/UCLA/Courses/csm152a/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/rom_16x784/rom_16x784.xci
# IP: The module: 'rom_16x784' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/psf/iCloud/UCLA/Courses/csm152a/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/rom_16x784/rom_16x784_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_16x784'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /media/psf/iCloud/UCLA/Courses/csm152a/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/rom_16x784/rom_16x784.xci
# IP: The module: 'rom_16x784' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/psf/iCloud/UCLA/Courses/csm152a/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/rom_16x784/rom_16x784_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_16x784'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
