# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/basys3.xdc

# IP: ip/rom_16x784/rom_16x784.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_16x784 || ORIG_REF_NAME==rom_16x784} -quiet] -quiet
