# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/matt/csm152a/lab_4_basys/lab_4_basys.cache/wt [current_project]
set_property parent.project_path /home/matt/csm152a/lab_4_basys/lab_4_basys.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/matt/.Xilinx/Vivado/2019.2/xhub/board_store} [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo /home/matt/csm152a/lab_4_basys/lab_4_basys.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/weights_l1_data_0.coe
add_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/weights_l1_data_1.coe
add_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/weights_l1_data_2.coe
add_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/weights_l1_data_4.coe
add_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/weights_l1_data_3.coe
add_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/weights_l1_data_5.coe
add_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/weights_l1_data_6.coe
add_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/weights_l1_data_7.coe
add_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/weights_l1_data_8.coe
add_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/weights_l1_data_9.coe
add_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/weights_l1_data_10.coe
add_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/weights_l1_data_11.coe
add_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/weights_l1_data_12.coe
add_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/weights_l1_data_13.coe
add_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/weights_l1_data_14.coe
add_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/weights_l1_data_15.coe
read_verilog /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/imports/lab_4/definitions.v
set_property file_type "Verilog Header" [get_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/imports/lab_4/definitions.v]
read_mem {
  /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/imports/python/biases_input_data
  /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/imports/python/biases_hidden_1_data
  /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/imports/python/weights_input_data
  /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/imports/python/weights_hidden_1_data
}
read_verilog -library xil_defaultlib {
  /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/imports/lab_4/fp_multiplier.v
  /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/imports/lab_4/parallel_adder_4.v
  /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/imports/lab_4/relu.v
  /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/imports/lab_4/simple_nn.v
  /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/imports/lab_4/parallel_adder_16.v
  /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/new/simple_blk_mem.v
  /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/new/mnist_network.v
  /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/new/simple_ps2.v
}
read_ip -quiet /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc]

read_ip -quiet /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_0/blk_mem_input_weights_0.xci
set_property used_in_implementation false [get_files -all /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_0/blk_mem_input_weights_0_ooc.xdc]

read_ip -quiet /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_1/blk_mem_input_weights_1.xci
set_property used_in_implementation false [get_files -all /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_1/blk_mem_input_weights_1_ooc.xdc]

read_ip -quiet /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_2/blk_mem_input_weights_2.xci
set_property used_in_implementation false [get_files -all /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_2/blk_mem_input_weights_2_ooc.xdc]

read_ip -quiet /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_3/blk_mem_input_weights_3.xci
set_property used_in_implementation false [get_files -all /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_3/blk_mem_input_weights_3_ooc.xdc]

read_ip -quiet /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_4/blk_mem_input_weights_4.xci
set_property used_in_implementation false [get_files -all /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_4/blk_mem_input_weights_4_ooc.xdc]

read_ip -quiet /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_5/blk_mem_input_weights_5.xci
set_property used_in_implementation false [get_files -all /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_5/blk_mem_input_weights_5_ooc.xdc]

read_ip -quiet /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_6/blk_mem_input_weights_6.xci
set_property used_in_implementation false [get_files -all /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_6/blk_mem_input_weights_6_ooc.xdc]

read_ip -quiet /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_7/blk_mem_input_weights_7.xci
set_property used_in_implementation false [get_files -all /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_7/blk_mem_input_weights_7_ooc.xdc]

read_ip -quiet /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_8/blk_mem_input_weights_8.xci
set_property used_in_implementation false [get_files -all /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_8/blk_mem_input_weights_8_ooc.xdc]

read_ip -quiet /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_9/blk_mem_input_weights_9.xci
set_property used_in_implementation false [get_files -all /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_9/blk_mem_input_weights_9_ooc.xdc]

read_ip -quiet /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_10/blk_mem_input_weights_10.xci
set_property used_in_implementation false [get_files -all /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_10/blk_mem_input_weights_10_ooc.xdc]

read_ip -quiet /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_11/blk_mem_input_weights_11.xci
set_property used_in_implementation false [get_files -all /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_11/blk_mem_input_weights_11_ooc.xdc]

read_ip -quiet /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_12/blk_mem_input_weights_12.xci
set_property used_in_implementation false [get_files -all /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_12/blk_mem_input_weights_12_ooc.xdc]

read_ip -quiet /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_13/blk_mem_input_weights_13.xci
set_property used_in_implementation false [get_files -all /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_13/blk_mem_input_weights_13_ooc.xdc]

read_ip -quiet /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_14/blk_mem_input_weights_14.xci
set_property used_in_implementation false [get_files -all /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_14/blk_mem_input_weights_14_ooc.xdc]

read_ip -quiet /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_15/blk_mem_input_weights_15.xci
set_property used_in_implementation false [get_files -all /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/sources_1/ip/blk_mem_input_weights_15/blk_mem_input_weights_15_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/constrs_1/new/basys3.xdc
set_property used_in_implementation false [get_files /home/matt/csm152a/lab_4_basys/lab_4_basys.srcs/constrs_1/new/basys3.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top simple_ps2 -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef simple_ps2.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file simple_ps2_utilization_synth.rpt -pb simple_ps2_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
